name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Load environment variables
        uses: actions/setup-dotenv@v2
        with:
          path: .env

      - name: Compile TypeScript
        run: npx tsc

      - name: Run script
        run: node lib/index.js
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          WEBHOOK_PROXY_URL: ${{ secrets.WEBHOOK_PROXY_URL }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
          APP_ID: ${{ secrets.APP_ID }}
