name: NodeJS 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        WEBHOOK_PROXY_URL: ${{ secrets.WEBHOOK_PROXY_URL }}
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        APP_ID: ${{ secrets.APP_ID }}
      run: |
        npm install
        npm run build
        npm start

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./lib  
